In [1]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [2]:
cd /content/gdrive/My Drive/colab

/content/gdrive/My Drive/colab


In [0]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [4]:
train = pd.read_excel('ecoli.train.xlsx')
test = pd.read_excel("ecoli.test.xlsx")
train.shape

(202, 8)

In [5]:
test.shape

(134, 8)

In [6]:
print(train.columns)

Index(['mcg', 'gvh', 'lip', 'asd', 'aac', 'alm1', 'alm2', 'class'], dtype='object')


In [7]:
class_name = input("Chooese the class")

Chooese the classclass


In [0]:
minmax_scaler = MinMaxScaler()

In [9]:
tr_ans = train[class_name]
ts_ans = test[class_name]
class_count = len(tr_ans.unique())
print(class_count)

8


In [0]:
tr_data = train.drop([class_name], axis=1)
ts_data = test.drop([class_name], axis=1)

In [11]:
ts_ans.dtype

dtype('O')

In [12]:
from sklearn.preprocessing import Imputer

rep_0 = Imputer(missing_values=0, strategy="mean", axis=0)

tr_data = rep_0.fit_transform(tr_data)
ts_data = rep_0.fit_transform(ts_data)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
tr_data = minmax_scaler.fit_transform(tr_data)
ts_data = minmax_scaler.transform(ts_data)
tr_ans, _ = tr_ans.factorize()
ts_ans, _ = ts_ans.factorize()
tr_ans = np.array(tr_ans)
ts_ans = np.array(ts_ans)

In [14]:
tr_data

array([[0.52941176, 0.18571429, 0.        , ..., 0.55555556, 0.2       ,
        0.34693878],
       [0.03529412, 0.34285714, 0.        , ..., 0.52777778, 0.31578947,
        0.43877551],
       [0.61176471, 0.34285714, 0.        , ..., 0.45833333, 0.33684211,
        0.45918367],
       ...,
       [0.61176471, 0.54285714, 0.        , ..., 0.375     , 0.33684211,
        0.29591837],
       [0.82352941, 0.57142857, 0.        , ..., 0.43055556, 0.66315789,
        0.29591837],
       [0.78823529, 0.58571429, 0.        , ..., 0.44444444, 0.31578947,
        0.31632653]])

In [0]:
import os
from datetime import datetime

In [0]:
#about tensorboard

# now = datetime.utcnow().strftime("&Y&m%d%H%M%S")
# root_logdir = "tf_logs"
# logdir = "{}/run-{}".format(root_logdir, now)
# #%tensorboard --logdir logs

# tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

In [0]:
import tensorflow as tf
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import ParameterGrid
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Dropout
import tensorflow.keras.metrics as km
from sklearn import metrics
from tensorflow.keras.regularizers import l2


In [0]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
from functools import partial

In [0]:
# real Version


# def create_model(hidden_layers = 1, neurons =1, init_mode = 'uniform', activation = 'elu'):
#   model = Sequential()
#   model.add(Dense(neurons, input_dim=len(tr_data.T), kernel_initializer=init_mode, activation=activation))
#   model.add(Dropout(0.2))
#   for i in range(hidden_layers):
    
#     model.add(Dense(neurons, kernel_initializer=init_mode))
#     model.add(BatchNormalization())
#     model.add(Activation(activation))
#     model.add(Dropout(0.2))
  
#   if class_count == 2:  
#     model.add(Dense(1,activation='sigmoid'))
#     model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#   elif class_count != 2:
#     model.add(Dense(class_count-1, activation='softmax'))
#     model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#   return model

# keras_model = KerasClassifier(build_fn=create_model, epochs=32, batch_size=16)
# print(keras_model)


# leaky_relu = tf.nn.leaky_relu
# hidden_layers = [10,15,20]
# neurons = [30, 70, 110]
# activation = ['elu', leaky_relu]
# init_mode = ['glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform']


# param_grid = dict(hidden_layers = hidden_layers, neurons = neurons, init_mode = init_mode, activation = activation)
# grid = GridSearchCV(estimator=keras_model, param_grid=param_grid, n_jobs= None, cv=2)
# print(grid)



# grid_result = grid.fit(tr_data, tr_ans)

# print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
# means = grid_result.cv_results_['mean_test_score']
# stds = grid_result.cv_results_['std_test_score']
# params = grid_result.cv_results_['params']

# for mean, stdev, param in zip(means, stds, params):
#     print("%f (%f) with: %r" % (mean, stdev, param))


# results = keras_model.predict(ts_data)

# correct_count = (results == ts_ans).sum()
# accuracy = correct_count / len(ts_ans)
# ts_ans = ts_ans.astype(float)
# pred = pred.astype(float
# precision, recall, fbeta_score, support = precision_recall_fscore_support(ts_ans, results)
# conf_mat = confusion_matrix(ts_ans, results)
# print("Accuracy = ", accuracy)
# print("Precision = ", precision)
# print('Recall = ', recall)
# print("fbeta_score = ", fbeta_score)
# print("Support = ", support)

In [0]:
# testbed Version


def create_model():
  model = Sequential()
  model.add(Dense(50, input_dim=len(tr_data.T), kernel_initializer='he_uniform',
                  activation='elu', kernel_regularizer=l2(0.001)))
  model.add(Dropout(0.2))
  for i in range(3):
    
    model.add(Dense(50, kernel_initializer='he_uniform', kernel_regularizer=l2(0.001)))
    model.add(BatchNormalization())
    model.add(Activation('elu'))
    model.add(Dropout(0.2))
  
  if class_count == 2:  
    model.add(Dense(1,activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  elif class_count != 2:
    model.add(Dense(class_count-1, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

In [21]:
keras_model = KerasClassifier(build_fn=create_model, epochs=16, batch_size=8)
print(keras_model)

In [22]:
model = KerasClassifier(build_fn=create_model, epochs=16, batch_size=8) 
model.fit(tr_data, tr_ans)
tr_pred = model.predict(tr_data)
pred = model.predict(ts_data)
pred

W0701 08:43:54.713594 139935138572160 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Epoch 1/16
202/202 [==============================] - 1s 4ms/sample - loss: nan - acc: 0.3812
Epoch 2/16
202/202 [==============================] - 0s 656us/sample - loss: nan - acc: 0.3911
Epoch 3/16
202/202 [==============================] - 0s 738us/sample - loss: nan - acc: 0.3911
Epoch 4/16
202/202 [==============================] - 0s 684us/sample - loss: nan - acc: 0.3911
Epoch 5/16
202/202 [==============================] - 0s 663us/sample - loss: nan - acc: 0.3911
Epoch 6/16
202/202 [==============================] - 0s 688us/sample - loss: nan - acc: 0.3911
Epoch 7/16
202/202 [==============================] - 0s 661us/sample - loss: nan - acc: 0.3911
Epoch 8/16
202/202 [==============================] - 0s 697us/sample - loss: nan - acc: 0.3911
Epoch 9/16
202/202 [==============================] - 0s 660us/sample - loss: nan - acc: 0.3911
Epoch 10/16
202/202 [==============================] - 0s 668us/sample - loss: nan - acc: 0.3911
Epoch 11/16
202/202 [====================

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [23]:
accuracy = accuracy_score(pred, ts_ans)
ts_ans = ts_ans.astype(float)
precision, recall, fbeta_score, support = precision_recall_fscore_support(ts_ans, pred)
conf_mat = confusion_matrix(ts_ans, pred)
print("Accuracy = ", accuracy)
print("Confusion Matrix")
print("{0}".format(metrics.confusion_matrix(ts_ans, pred)))
print("")
print("Classification Report")
print(metrics.classification_report(ts_ans, pred))




Accuracy =  0.47761194029850745
Confusion Matrix
[[64  0  0  0  0]
 [29  0  0  0  0]
 [11  0  0  0  0]
 [10  0  0  0  0]
 [20  0  0  0  0]]

Classification Report
              precision    recall  f1-score   support

         0.0       0.48      1.00      0.65        64
         1.0       0.00      0.00      0.00        29
         2.0       0.00      0.00      0.00        11
         3.0       0.00      0.00      0.00        10
         4.0       0.00      0.00      0.00        20

    accuracy                           0.48       134
   macro avg       0.10      0.20      0.13       134
weighted avg       0.23      0.48      0.31       134



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
