In [1]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [2]:
cd /content/gdrive/My Drive/colab

/content/gdrive/My Drive/colab


In [0]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [4]:
train = pd.read_excel('bupa.train.xlsx')
test = pd.read_excel("bupa.test.xlsx")
train.shape

(207, 7)

In [5]:
test.shape

(138, 7)

In [6]:
print(train.columns)

Index(['mcv', 'alkphos', 'sgpt', 'sgot', 'gammagt', 'drinks', 'selector'], dtype='object')


In [7]:
class_name = input("Chooese the class")

Chooese the classselector


In [0]:
minmax_scaler = MinMaxScaler()

In [9]:
tr_ans = train[class_name]
ts_ans = test[class_name]
class_count = len(tr_ans.unique())
print(class_count)

2


In [0]:
tr_data = train.drop([class_name], axis=1)
ts_data = test.drop([class_name], axis=1)

In [11]:
ts_ans.dtype

dtype('int64')

In [12]:
from sklearn.preprocessing import Imputer

rep_0 = Imputer(missing_values=0, strategy="mean", axis=0)

tr_data = rep_0.fit_transform(tr_data)
ts_data = rep_0.fit_transform(ts_data)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
tr_data = minmax_scaler.fit_transform(tr_data)
ts_data = minmax_scaler.transform(ts_data)
tr_ans, _ = tr_ans.factorize()
ts_ans, _ = ts_ans.factorize()
tr_ans = np.array(tr_ans)
ts_ans = np.array(ts_ans)

In [14]:
tr_data

array([[0.52631579, 0.6969697 , 0.24657534, 0.22535211, 0.0890411 ,
        0.16320513],
       [0.68421053, 0.55555556, 0.17123288, 0.18309859, 0.10616438,
        0.16320513],
       [0.57894737, 0.47474747, 0.02054795, 0.23943662, 0.01712329,
        0.16320513],
       ...,
       [0.57894737, 0.64646465, 0.04109589, 0.16901408, 0.02054795,
        0.48717949],
       [0.81578947, 0.46464646, 0.30136986, 0.45070423, 0.67808219,
        0.58974359],
       [0.86842105, 0.76767677, 0.32876712, 0.47887324, 0.20547945,
        1.        ]])

In [0]:
import os
from datetime import datetime

In [0]:
#about tensorboard

# now = datetime.utcnow().strftime("&Y&m%d%H%M%S")
# root_logdir = "tf_logs"
# logdir = "{}/run-{}".format(root_logdir, now)
# #%tensorboard --logdir logs

# tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

In [0]:
import tensorflow as tf
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import ParameterGrid
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Dropout
import tensorflow.keras.metrics as km
from sklearn import metrics
from tensorflow.keras.regularizers import l2


In [0]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
from functools import partial

In [0]:
# real Version


# def create_model(hidden_layers = 1, neurons =1, init_mode = 'uniform', activation = 'elu'):
#   model = Sequential()
#   model.add(Dense(neurons, input_dim=len(tr_data.T), kernel_initializer=init_mode, activation=activation))
#   model.add(Dropout(0.2))
#   for i in range(hidden_layers):
    
#     model.add(Dense(neurons, kernel_initializer=init_mode))
#     model.add(BatchNormalization())
#     model.add(Activation(activation))
#     model.add(Dropout(0.2))
  
#   if class_count == 2:  
#     model.add(Dense(1,activation='sigmoid'))
#     model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#   elif class_count != 2:
#     model.add(Dense(class_count-1, activation='softmax'))
#     model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#   return model

# keras_model = KerasClassifier(build_fn=create_model, epochs=32, batch_size=16)
# print(keras_model)


# leaky_relu = tf.nn.leaky_relu
# hidden_layers = [10,15,20]
# neurons = [30, 70, 110]
# activation = ['elu', leaky_relu]
# init_mode = ['glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform']


# param_grid = dict(hidden_layers = hidden_layers, neurons = neurons, init_mode = init_mode, activation = activation)
# grid = GridSearchCV(estimator=keras_model, param_grid=param_grid, n_jobs= None, cv=2)
# print(grid)



# grid_result = grid.fit(tr_data, tr_ans)

# print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
# means = grid_result.cv_results_['mean_test_score']
# stds = grid_result.cv_results_['std_test_score']
# params = grid_result.cv_results_['params']

# for mean, stdev, param in zip(means, stds, params):
#     print("%f (%f) with: %r" % (mean, stdev, param))


# results = keras_model.predict(ts_data)

# correct_count = (results == ts_ans).sum()
# accuracy = correct_count / len(ts_ans)
# ts_ans = ts_ans.astype(float)
# pred = pred.astype(float
# precision, recall, fbeta_score, support = precision_recall_fscore_support(ts_ans, results)
# conf_mat = confusion_matrix(ts_ans, results)
# print("Accuracy = ", accuracy)
# print("Precision = ", precision)
# print('Recall = ', recall)
# print("fbeta_score = ", fbeta_score)
# print("Support = ", support)

In [0]:
# testbed Version


def create_model():
  model = Sequential()
  model.add(Dense(50, input_dim=len(tr_data.T), kernel_initializer='he_uniform',
                  activation='elu', kernel_regularizer=l2(0.001)))
  model.add(Dropout(0.2))
  for i in range(3):
    
    model.add(Dense(50, kernel_initializer='he_uniform', kernel_regularizer=l2(0.001)))
    model.add(BatchNormalization())
    model.add(Activation('elu'))
    model.add(Dropout(0.2))
  
  if class_count == 2:  
    model.add(Dense(1,activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  elif class_count != 2:
    model.add(Dense(class_count-1, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

In [21]:
keras_model = KerasClassifier(build_fn=create_model, epochs=16, batch_size=8)
print(keras_model)

In [22]:
model = KerasClassifier(build_fn=create_model, epochs=16, batch_size=8) 
model.fit(tr_data, tr_ans)
tr_pred = model.predict(tr_data)
pred = model.predict(ts_data)
pred

W0701 09:10:10.837710 139714349193088 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0701 09:10:10.882512 139714349193088 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/16
207/207 [==============================] - 1s 4ms/sample - loss: 1.2061 - acc: 0.5314
Epoch 2/16
207/207 [==============================] - 0s 697us/sample - loss: 1.1644 - acc: 0.5266
Epoch 3/16
207/207 [==============================] - 0s 674us/sample - loss: 1.1362 - acc: 0.5700
Epoch 4/16
207/207 [==============================] - 0s 700us/sample - loss: 1.1427 - acc: 0.5362
Epoch 5/16
207/207 [==============================] - 0s 685us/sample - loss: 1.1834 - acc: 0.5700
Epoch 6/16
207/207 [==============================] - 0s 844us/sample - loss: 1.1633 - acc: 0.5411
Epoch 7/16
207/207 [==============================] - 0s 707us/sample - loss: 1.1007 - acc: 0.5990
Epoch 8/16
207/207 [==============================] - 0s 702us/sample - loss: 1.1195 - acc: 0.5652
Epoch 9/16
207/207 [==============================] - 0s 717us/sample - loss: 1.0812 - acc: 0.6087
Epoch 10/16
207/207 [==============================] - 0s 689us/sample - loss: 1.0529 - acc: 0.6039
Epoch 11/16

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
    

In [23]:
accuracy = accuracy_score(pred, ts_ans)
ts_ans = ts_ans.astype(float)
precision, recall, fbeta_score, support = precision_recall_fscore_support(ts_ans, pred)
conf_mat = confusion_matrix(ts_ans, pred)
print("Accuracy = ", accuracy)
print("Confusion Matrix")
print("{0}".format(metrics.confusion_matrix(ts_ans, pred)))
print("")
print("Classification Report")
print(metrics.classification_report(ts_ans, pred))




Accuracy =  0.2826086956521739
Confusion Matrix
[[11 68]
 [31 28]]

Classification Report
              precision    recall  f1-score   support

         0.0       0.26      0.14      0.18        79
         1.0       0.29      0.47      0.36        59

    accuracy                           0.28       138
   macro avg       0.28      0.31      0.27       138
weighted avg       0.27      0.28      0.26       138

