In [1]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [2]:
cd /content/gdrive/My Drive/colab

/content/gdrive/My Drive/colab


In [0]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [4]:
train = pd.read_excel('parkinsons.train.xlsx')
test = pd.read_excel("parkinsons.test.xlsx")
train.shape

(117, 23)

In [5]:
test.shape

(78, 23)

In [6]:
print(train.columns)

Index(['MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP',
       'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA',
       'spread1', 'spread2', 'D2', 'PPE'],
      dtype='object')


In [7]:
class_name = input("Chooese the class")

Chooese the classstatus


In [0]:
minmax_scaler = MinMaxScaler()

In [9]:
tr_ans = train[class_name]
ts_ans = test[class_name]
class_count = len(tr_ans.unique())
print(class_count)

2


In [0]:
tr_data = train.drop([class_name], axis=1)
ts_data = test.drop([class_name], axis=1)

In [11]:
ts_ans.dtype

dtype('int64')

In [12]:
from sklearn.preprocessing import Imputer

rep_0 = Imputer(missing_values=0, strategy="mean", axis=0)

tr_data = rep_0.fit_transform(tr_data)
ts_data = rep_0.fit_transform(ts_data)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
tr_data = minmax_scaler.fit_transform(tr_data)
ts_data = minmax_scaler.transform(ts_data)
tr_ans, _ = tr_ans.factorize()
ts_ans, _ = ts_ans.factorize()
tr_ans = np.array(tr_ans)
ts_ans = np.array(ts_ans)

In [14]:
tr_data

array([[0.18430827, 0.1123018 , 0.05541038, ..., 0.57385527, 0.39066128,
        0.4973096 ],
       [0.19832685, 0.09463474, 0.28134694, ..., 0.7339001 , 0.47314522,
        0.67132602],
       [0.16503854, 0.05882077, 0.26817089, ..., 0.67735361, 0.40881938,
        0.59668246],
       ...,
       [0.50273036, 0.28117821, 0.05127832, ..., 0.32367463, 0.55896743,
        0.18057983],
       [0.6428929 , 0.60167645, 0.05486914, ..., 0.43715436, 0.31822198,
        0.16313677],
       [0.73327434, 0.32257287, 0.07273013, ..., 0.39827792, 0.50367281,
        0.21545975]])

In [0]:
import os
from datetime import datetime

In [0]:
#about tensorboard

# now = datetime.utcnow().strftime("&Y&m%d%H%M%S")
# root_logdir = "tf_logs"
# logdir = "{}/run-{}".format(root_logdir, now)
# #%tensorboard --logdir logs

# tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

In [0]:
import tensorflow as tf
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import ParameterGrid
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Dropout
import tensorflow.keras.metrics as km
from sklearn import metrics
from tensorflow.keras.regularizers import l2


In [0]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
from functools import partial

In [0]:
# real Version


# def create_model(hidden_layers = 1, neurons =1, init_mode = 'uniform', activation = 'elu'):
#   model = Sequential()
#   model.add(Dense(neurons, input_dim=len(tr_data.T), kernel_initializer=init_mode, activation=activation))
#   model.add(Dropout(0.2))
#   for i in range(hidden_layers):
    
#     model.add(Dense(neurons, kernel_initializer=init_mode))
#     model.add(BatchNormalization())
#     model.add(Activation(activation))
#     model.add(Dropout(0.2))
  
#   if class_count == 2:  
#     model.add(Dense(1,activation='sigmoid'))
#     model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#   elif class_count != 2:
#     model.add(Dense(class_count-1, activation='softmax'))
#     model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#   return model

# keras_model = KerasClassifier(build_fn=create_model, epochs=32, batch_size=16)
# print(keras_model)


# leaky_relu = tf.nn.leaky_relu
# hidden_layers = [10,15,20]
# neurons = [30, 70, 110]
# activation = ['elu', leaky_relu]
# init_mode = ['glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform']


# param_grid = dict(hidden_layers = hidden_layers, neurons = neurons, init_mode = init_mode, activation = activation)
# grid = GridSearchCV(estimator=keras_model, param_grid=param_grid, n_jobs= None, cv=2)
# print(grid)



# grid_result = grid.fit(tr_data, tr_ans)

# print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
# means = grid_result.cv_results_['mean_test_score']
# stds = grid_result.cv_results_['std_test_score']
# params = grid_result.cv_results_['params']

# for mean, stdev, param in zip(means, stds, params):
#     print("%f (%f) with: %r" % (mean, stdev, param))


# results = keras_model.predict(ts_data)

# correct_count = (results == ts_ans).sum()
# accuracy = correct_count / len(ts_ans)
# ts_ans = ts_ans.astype(float)
# pred = pred.astype(float
# precision, recall, fbeta_score, support = precision_recall_fscore_support(ts_ans, results)
# conf_mat = confusion_matrix(ts_ans, results)
# print("Accuracy = ", accuracy)
# print("Precision = ", precision)
# print('Recall = ', recall)
# print("fbeta_score = ", fbeta_score)
# print("Support = ", support)

In [0]:
# testbed Version


def create_model():
  model = Sequential()
  model.add(Dense(50, input_dim=len(tr_data.T), kernel_initializer='he_uniform',
                  activation='elu', kernel_regularizer=l2(0.001)))
  model.add(Dropout(0.2))
  for i in range(3):
    
    model.add(Dense(50, kernel_initializer='he_uniform', kernel_regularizer=l2(0.001)))
    model.add(BatchNormalization())
    model.add(Activation('elu'))
    model.add(Dropout(0.2))
  
  if class_count == 2:  
    model.add(Dense(1,activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  elif class_count != 2:
    model.add(Dense(class_count-1, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

In [21]:
keras_model = KerasClassifier(build_fn=create_model, epochs=16, batch_size=8)
print(keras_model)

In [22]:
model = KerasClassifier(build_fn=create_model, epochs=16, batch_size=8) 
model.fit(tr_data, tr_ans)
tr_pred = model.predict(tr_data)
pred = model.predict(ts_data)
pred

W0701 08:49:12.864962 139861863802752 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0701 08:49:12.906310 139861863802752 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/16
117/117 [==============================] - 1s 6ms/sample - loss: 1.1151 - acc: 0.5897
Epoch 2/16
117/117 [==============================] - 0s 697us/sample - loss: 0.9903 - acc: 0.6667
Epoch 3/16
117/117 [==============================] - 0s 708us/sample - loss: 0.9431 - acc: 0.7094
Epoch 4/16
117/117 [==============================] - 0s 708us/sample - loss: 0.9101 - acc: 0.7521
Epoch 5/16
117/117 [==============================] - 0s 696us/sample - loss: 0.9283 - acc: 0.6752
Epoch 6/16
117/117 [==============================] - 0s 747us/sample - loss: 0.8363 - acc: 0.7949
Epoch 7/16
117/117 [==============================] - 0s 707us/sample - loss: 0.9007 - acc: 0.7009
Epoch 8/16
117/117 [==============================] - 0s 697us/sample - loss: 0.8716 - acc: 0.7607
Epoch 9/16
117/117 [==============================] - 0s 721us/sample - loss: 0.8517 - acc: 0.7692
Epoch 10/16
117/117 [==============================] - 0s 694us/sample - loss: 0.8391 - acc: 0.8034
Epoch 11/16

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0]])

In [23]:
accuracy = accuracy_score(pred, ts_ans)
ts_ans = ts_ans.astype(float)
precision, recall, fbeta_score, support = precision_recall_fscore_support(ts_ans, pred)
conf_mat = confusion_matrix(ts_ans, pred)
print("Accuracy = ", accuracy)
print("Confusion Matrix")
print("{0}".format(metrics.confusion_matrix(ts_ans, pred)))
print("")
print("Classification Report")
print(metrics.classification_report(ts_ans, pred))




Accuracy =  0.8846153846153846
Confusion Matrix
[[57  2]
 [ 7 12]]

Classification Report
              precision    recall  f1-score   support

         0.0       0.89      0.97      0.93        59
         1.0       0.86      0.63      0.73        19

    accuracy                           0.88        78
   macro avg       0.87      0.80      0.83        78
weighted avg       0.88      0.88      0.88        78

