In [1]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [2]:
cd /content/gdrive/My Drive/colab

/content/gdrive/My Drive/colab


In [0]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [39]:
train = pd.read_excel('pima-indians-diabetes.train.xlsx')
test = pd.read_excel("pima-indians-diabetes.test.xlsx")
train.shape

(461, 9)

In [40]:
test.shape

(307, 9)

In [41]:
print(train.columns)

Index(['Number of times pregnant',
       'Plasma glucose concentration a 2 hours in an oral glucose tolerance test',
       'Diastolic blood pressure (mm Hg)', 'Triceps skin fold thickness (mm)',
       '2-Hour serum insulin (mu U/ml)',
       'Body mass index (weight in kg/(height in m)^2)',
       'Diabetes pedigree function', 'Age (years)', 'Class variable (0 or 1)'],
      dtype='object')


In [42]:
class_name = input("Chooese the class")

Chooese the classClass variable (0 or 1)


In [0]:
minmax_scaler = MinMaxScaler()

In [43]:
tr_ans = train[class_name]
ts_ans = test[class_name]
class_count = len(tr_ans.unique())
print(class_count)

2


In [0]:
tr_data = train.drop([class_name], axis=1)
ts_data = test.drop([class_name], axis=1)

In [44]:
ts_ans.dtype

dtype('int64')

In [45]:
from sklearn.preprocessing import Imputer

rep_0 = Imputer(missing_values=0, strategy="mean", axis=0)

tr_data = rep_0.fit_transform(tr_data)
ts_data = rep_0.fit_transform(ts_data)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
# tr_data = minmax_scaler.fit_transform(tr_data)
# ts_data = minmax_scaler.transform(ts_data)
tr_ans, _ = tr_ans.factorize()
ts_ans, _ = ts_ans.factorize()
tr_ans = np.array(tr_ans)
ts_ans = np.array(ts_ans)

In [47]:
tr_ans

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,

In [0]:
import os
from datetime import datetime

In [0]:
#about tensorboard

# now = datetime.utcnow().strftime("&Y&m%d%H%M%S")
# root_logdir = "tf_logs"
# logdir = "{}/run-{}".format(root_logdir, now)
# #%tensorboard --logdir logs

# tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

In [0]:
import tensorflow as tf
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import ParameterGrid
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Dropout
import tensorflow.keras.metrics as km
from sklearn import metrics
from tensorflow.keras.regularizers import l2


In [0]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
from functools import partial

In [0]:
# real Version


# def create_model(hidden_layers = 1, neurons =1, init_mode = 'uniform', activation = 'elu'):
#   model = Sequential()
#   model.add(Dense(neurons, input_dim=len(tr_data.T), kernel_initializer=init_mode, activation=activation))
#   model.add(Dropout(0.2))
#   for i in range(hidden_layers):
    
#     model.add(Dense(neurons, kernel_initializer=init_mode))
#     model.add(BatchNormalization())
#     model.add(Activation(activation))
#     model.add(Dropout(0.2))
  
#   if class_count == 2:  
#     model.add(Dense(1,activation='sigmoid'))
#     model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#   elif class_count != 2:
#     model.add(Dense(class_count-1, activation='softmax'))
#     model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#   return model

# keras_model = KerasClassifier(build_fn=create_model, epochs=32, batch_size=16)
# print(keras_model)


# leaky_relu = tf.nn.leaky_relu
# hidden_layers = [10,15,20]
# neurons = [30, 70, 110]
# activation = ['elu', leaky_relu]
# init_mode = ['glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform']


# param_grid = dict(hidden_layers = hidden_layers, neurons = neurons, init_mode = init_mode, activation = activation)
# grid = GridSearchCV(estimator=keras_model, param_grid=param_grid, n_jobs= None, cv=2)
# print(grid)



# grid_result = grid.fit(tr_data, tr_ans)

# print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
# means = grid_result.cv_results_['mean_test_score']
# stds = grid_result.cv_results_['std_test_score']
# params = grid_result.cv_results_['params']

# for mean, stdev, param in zip(means, stds, params):
#     print("%f (%f) with: %r" % (mean, stdev, param))


# results = keras_model.predict(ts_data)

# correct_count = (results == ts_ans).sum()
# accuracy = correct_count / len(ts_ans)
# ts_ans = ts_ans.astype(float)
# pred = pred.astype(float
# precision, recall, fbeta_score, support = precision_recall_fscore_support(ts_ans, results)
# conf_mat = confusion_matrix(ts_ans, results)
# print("Accuracy = ", accuracy)
# print("Precision = ", precision)
# print('Recall = ', recall)
# print("fbeta_score = ", fbeta_score)
# print("Support = ", support)

In [0]:
# testbed Version


def create_model():
  model = Sequential()
  model.add(Dense(len(tr_data.T), input_dim=len(tr_data.T), kernel_initializer='he_uniform',
                  activation='elu'))
  
  model.add(Dense(64, kernel_initializer='he_uniform'))
  model.add(BatchNormalization())
  model.add(Activation('elu'))
  model.add(Dropout(0.2))
  
  model.add(Dense(32, kernel_initializer='he_uniform'))
  model.add(BatchNormalization())
  model.add(Activation('elu'))
  model.add(Dropout(0.2))
  
  if class_count == 2:  
    model.add(Dense(1,activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  elif class_count != 2:
    model.add(Dense(class_count-1, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

In [20]:
keras_model = KerasClassifier(build_fn=create_model, epochs=16, batch_size=8)
print(keras_model)

In [21]:
model = KerasClassifier(build_fn=create_model, epochs=128, batch_size=8) 
model.fit(tr_data, tr_ans)
tr_pred = model.predict(tr_data)
pred = model.predict(ts_data)
pred

W0702 09:04:33.524669 140245270235008 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0702 09:04:33.566143 140245270235008 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/128
461/461 [==============================] - 1s 2ms/sample - loss: 0.7736 - acc: 0.5553
Epoch 2/128
461/461 [==============================] - 0s 606us/sample - loss: 0.7378 - acc: 0.5748
Epoch 3/128
461/461 [==============================] - 0s 603us/sample - loss: 0.6387 - acc: 0.6529
Epoch 4/128
461/461 [==============================] - 0s 632us/sample - loss: 0.6221 - acc: 0.6638
Epoch 5/128
461/461 [==============================] - 0s 589us/sample - loss: 0.6185 - acc: 0.6638
Epoch 6/128
461/461 [==============================] - 0s 598us/sample - loss: 0.6217 - acc: 0.6746
Epoch 7/128
461/461 [==============================] - 0s 585us/sample - loss: 0.6016 - acc: 0.6725
Epoch 8/128
461/461 [==============================] - 0s 649us/sample - loss: 0.6066 - acc: 0.6876
Epoch 9/128
461/461 [==============================] - 0s 603us/sample - loss: 0.5727 - acc: 0.7007
Epoch 10/128
461/461 [==============================] - 0s 590us/sample - loss: 0.5696 - acc: 0.7137
E

array([[0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
    

In [22]:
accuracy = accuracy_score(pred, ts_ans)
ts_ans = ts_ans.astype(float)
precision, recall, fbeta_score, support = precision_recall_fscore_support(ts_ans, pred)
conf_mat = confusion_matrix(ts_ans, pred)
print("Accuracy = ", accuracy)
print("Confusion Matrix")
print("{0}".format(metrics.confusion_matrix(ts_ans, pred)))
print("")
print("Classification Report")
print(metrics.classification_report(ts_ans, pred))




Accuracy =  0.7817589576547231
Confusion Matrix
[[174  36]
 [ 31  66]]

Classification Report
              precision    recall  f1-score   support

         0.0       0.85      0.83      0.84       210
         1.0       0.65      0.68      0.66        97

    accuracy                           0.78       307
   macro avg       0.75      0.75      0.75       307
weighted avg       0.79      0.78      0.78       307

